#!/usr/bin/env python3
"""
ChainDeploy — Stellar testnet setup: keys, Friendbot, WASM build, contract deploy, init.

Requires: cargo (wasm32 target), stellar CLI, Python deps (see scripts/requirements.txt).

Writes:
  - .env.chaindemo          — combined secrets for docker / backend / scripts (gitignored)
  - backend/.env.generated  — same keys with DATABASE_URL placeholder for local dev
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

from stellar_sdk.keypair import Keypair

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "scripts"))

from stellar_tools import (  # noqa: E402
    REPO_ROOT,
    DEFAULT_RPC,
    TESTNET_PASSPHRASE,
    build_wasm_release,
    check_cli_or_exit,
    deploy_contract,
    deployment_decision_init,
    deployment_decision_set_team_approvers,
    friendbot_fund,
    wasm_path,
)


def table(rows: list[list[str]], headers: list[str]) -> str:
    widths = [len(h) for h in headers]
    for row in rows:
        for i, cell in enumerate(row):
            widths[i] = max(widths[i], len(cell))
    sep = "-+-".join("-" * w for w in widths)
    head = " | ".join(h.ljust(widths[i]) for i, h in enumerate(headers))
    body = "\n".join(
        " | ".join(row[i].ljust(widths[i]) for i in range(len(headers))) for row in rows
    )
    return f"{head}\n{sep}\n{body}"


def main() -> None:
    parser = argparse.ArgumentParser(description="ChainDeploy Stellar testnet bootstrap")
    parser.add_argument(
        "--skip-build",
        action="store_true",
        help="Skip cargo wasm build (use existing artifacts)",
    )
    parser.add_argument(
        "--skip-deploy",
        action="store_true",
        help="Only generate keys + fund + write env templates (no stellar deploy)",
    )
    args = parser.parse_args()

    stellar_bin = None if args.skip_deploy else check_cli_or_exit()

    print("Generating keypairs (deployer + 2 approvers)…")
    deployer = Keypair.random()
    approver_a = Keypair.random()
    approver_b = Keypair.random()

    keys: list[tuple[str, Keypair]] = [
        ("DEPLOYER", deployer),
        ("APPROVER_1", approver_a),
        ("APPROVER_2", approver_b),
    ]

    print("Funding via Friendbot (testnet)…")
    for name, kp in keys:
        print(f"  • {name}: {kp.public_key}")
        friendbot_fund(kp.public_key, "testnet")

    cid_decision = ""
    cid_multisig = ""
    cid_rollback = ""

    if not args.skip_deploy:
        assert stellar_bin is not None
        if not args.skip_build:
            print("Building WASM (wasm32-unknown-unknown release)…")
            build_wasm_release()

        rpc = os.environ.get("SOROBAN_RPC_URL", DEFAULT_RPC)
        print("Deploying contracts…")
        cid_decision = deploy_contract(
            wasm=wasm_path("deployment_decision"),
            source_secret=deployer.secret,
            rpc_url=rpc,
            network_passphrase=TESTNET_PASSPHRASE,
            stellar_bin=stellar_bin,
        )
        print(f"  deployment_decision → {cid_decision}")
        cid_multisig = deploy_contract(
            wasm=wasm_path("multisig_approval"),
            source_secret=deployer.secret,
            rpc_url=rpc,
            network_passphrase=TESTNET_PASSPHRASE,
            stellar_bin=stellar_bin,
        )
        print(f"  multisig_approval → {cid_multisig}")
        cid_rollback = deploy_contract(
            wasm=wasm_path("rollback_engine"),
            source_secret=deployer.secret,
            rpc_url=rpc,
            network_passphrase=TESTNET_PASSPHRASE,
            stellar_bin=stellar_bin,
        )
        print(f"  rollback_engine → {cid_rollback}")

        print("Initializing DeploymentDecision (init admin = deployer)…")
        deployment_decision_init(
            cid_decision,
            deployer,
            rpc_url=rpc,
            network_passphrase=TESTNET_PASSPHRASE,
        )
        print("Setting team approvers (multi-sig eligible list)…")
        deployment_decision_set_team_approvers(
            cid_decision,
            deployer,
            [approver_a.public_key, approver_b.public_key],
            rpc_url=rpc,
            network_passphrase=TESTNET_PASSPHRASE,
        )

    env_chaindemo = REPO_ROOT / ".env.chaindemo"
    env_backend = REPO_ROOT / "backend" / ".env.generated"

    lines = [
        "# Generated by scripts/setup_stellar.py — do not commit secrets",
        "",
        "STELLAR_NETWORK=testnet",
        f"SOROBAN_RPC_URL={DEFAULT_RPC}",
        "HORIZON_URL=https://horizon-testnet.stellar.org",
        f"STELLAR_NETWORK_PASSPHRASE={TESTNET_PASSPHRASE}",
        "",
        f"CHAIN_DEPLOY_DEPLOYER_SECRET={deployer.secret}",
        f"CHAIN_DEPLOY_APPROVER_1_SECRET={approver_a.secret}",
        f"CHAIN_DEPLOY_APPROVER_2_SECRET={approver_b.secret}",
        "",
        f"CHAIN_DEPLOY_DEPLOYER_PUBLIC={deployer.public_key}",
        f"CHAIN_DEPLOY_APPROVER_1_PUBLIC={approver_a.public_key}",
        f"CHAIN_DEPLOY_APPROVER_2_PUBLIC={approver_b.public_key}",
        "",
        f"DEPLOYMENT_DECISION_CONTRACT_ID={cid_decision}",
        f"MULTISIG_APPROVAL_CONTRACT_ID={cid_multisig}",
        f"ROLLBACK_ENGINE_CONTRACT_ID={cid_rollback}",
        "",
        "# Default for evaluate() when omitted from JSON (dev/demo)",
        f"CHAIN_DEPLOY_DEFAULT_DEPLOYER_SECRET={deployer.secret}",
        "",
    ]

    backend_extra = [
        "# Merge into backend/.env or docker-compose env",
        "DATABASE_URL=postgresql+asyncpg://chaindeploy:chaindeploy@127.0.0.1:5432/chaindeploy",
        "CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000",
        "DASHBOARD_BASE_URL=http://localhost:3000",
        "CI_WEBHOOK_TOKEN=Z85zOSUzTqS0QS99qZVFtG-2y_Ut6pqErZdRvH3XMcU",
    ]

    env_chaindemo.write_text("\n".join(lines) + "\n".join(["", *backend_extra]) + "\n", encoding="utf-8")
    env_backend.write_text("\n".join(lines + backend_extra) + "\n", encoding="utf-8")

    print()
    print("═" * 72)
    print(" ChainDeploy — Stellar testnet setup summary")
    print("═" * 72)
    print()
    hdr = ["Role", "Public (G…)", "Secret saved as"]
    summary_rows = [
        [
            "Deployer",
            deployer.public_key[:16] + "…",
            "CHAIN_DEPLOY_DEPLOYER_SECRET",
        ],
        [
            "Approver 1",
            approver_a.public_key[:16] + "…",
            "CHAIN_DEPLOY_APPROVER_1_SECRET",
        ],
        [
            "Approver 2",
            approver_b.public_key[:16] + "…",
            "CHAIN_DEPLOY_APPROVER_2_SECRET",
        ],
    ]
    print(table(summary_rows, hdr))
    print()
    ch = ["Contract", "Contract ID"]
    crows = [
        ["DeploymentDecision", cid_decision or "(not deployed)"],
        ["MultiSigApproval", cid_multisig or "(not deployed)"],
        ["RollbackEngine", cid_rollback or "(not deployed)"],
    ]
    print(table(crows, ch))
    print()
    print(f"Wrote: {env_chaindemo}")
    print(f"Wrote: {env_backend}")
    print()
    print("Next: merge backend/.env.generated into backend/.env, source .env.chaindemo for demos,")
    print("      export contract vars to docker-compose, run `docker compose up --build`.")
    print()


if __name__ == "__main__":
    main()
